Repository TEAM-MODDY/moddy-web, pull requests merged in 2024-04, with the labels that each got.

#431 [ApplicationPage] box-shadow QA
  src/views/@common/assets/images/btn_hair1_default.png
  src/views/@common/assets/images/btn_hair1_selected.png
  src/views/@common/assets/images/btn_hair2_default.png
  src/views/@common/assets/images/btn_hair2_selected.png
  src/views/@common/assets/images/btn_hair3_default.png
  src/views/@common/assets/images/btn_hair3_selected.png
  src/views/@common/assets/images/btn_hair4_default.png
  src/views/@common/assets/images/btn_hair4_selected.png
  src/views/ApplicationPage/components/DefaultInfo.tsx
  src/views/ApplicationPage/components/HairTypeInput.tsx
Labels: ApplicationPage ✍🏻, qa 🔫

#429 [ApplicationPage] 시술 내역 드롭다운 컴포넌트 분리
  src/recoil/atoms/applicationState.ts
  src/views/ApplicationPage/components/DropDown.tsx
  src/views/ApplicationPage/components/ServiceHistory.tsx
  src/views/ApplicationPage/components/ServiceHistoryListItem.tsx
Labels: ApplicationPage ✍🏻, refactor ♻️

#436 [MyPage]디자이너 정보 수정 퍼블리싱
  src/App.tsx
  src/views/@common/components/TitleField.tsx
  src/views/@common/constants/days.ts
  src/views/MyPage/components/DesignerInfoSection.tsx
  src/views/MyPage/components/EditInfoPage.tsx
  src/views/MyPage/components/MyInfo.tsx
  src/views/MyPage/components/MyMenuList.tsx
  src/views/MyPage/constants/message.ts
  src/views/SignUpPage/components/4_샵정보/ShopInfo.tsx
Labels: publish 🎨, MyPage 🙋🏻

#440 [MyPage]기본정보 바탕으로 Clicked 처리 및 상태 변화 관리
  src/App.tsx
  src/pages/EditInfoPage.tsx
  src/views/@common/components/PostCode.tsx
  src/views/@common/components/ProfileUpload.tsx
  src/views/@common/constants/days.ts
  src/views/EditInfoPage/components/DesignerEditInfoSection.tsx
  src/views/EditInfoPage/constants/dummy.ts
  src/views/EditInfoPage/constants/message.ts
  src/views/EditInfoPage/hooks/.gitkeep
  src/views/EditInfoPage/utils/.gitkeep
  src/views/MyPage/components/DesignerInfoSection.tsx
  src/views/MyPage/components/EditInfoPage.tsx
  src/views/SignUpPage/components/4_샵정보/ShopInfo.tsx
Labels: feature ✨, EditPage✍️

#444 [EditPage] 모델 정보 수정 뷰 퍼블리싱
  src/pages/EditInfoPage.tsx
  src/views/@common/assets/icons/ic_close_smblue.svg
  src/views/@common/assets/icons/index.ts
  src/views/@common/components/RegionItem.tsx
  src/views/EditInfoPage/components/ModelEditInfoSection.tsx
  src/views/MyPage/constants/.gitkeep
  src/views/MyPage/hooks/.gitkeep
  src/views/SignUpPage/assets/icons/index.ts
  src/views/SignUpPage/components/3_선호지역선택/PreferRegion.tsx
Labels: publish 🎨, EditPage🛠

#448 [SignUpPage] 디자이너 회원가입 라이팅 수정
  src/styles/Theme.ts
  src/styles/style.d.ts
  src/views/@common/assets/icons/ic_right_grey30.svg
  src/views/@common/assets/icons/index.ts
  src/views/SignUpPage/components/7_오픈채팅링크/OpenChatLink.tsx
  src/views/SignUpPage/constants/message.ts
Labels: SignUpPage 👤

#447 [EditPage]Get, Put api 연결
  src/pages/MyPage.tsx
  src/views/EditInfoPage/components/DesignerEditInfoSection.tsx
  src/views/EditInfoPage/hooks/useGetDesignerEdit.ts
  src/views/EditInfoPage/hooks/usePutDesignerEdit.ts
  src/views/EditInfoPage/utils/type.ts
  src/views/SignUpPage/components/4_샵정보/ShopInfo.tsx
  src/views/SignUpPage/enterProfileProp.ts
Labels: api 📡, EditPage🛠

#451 [EditPage] GET API
  src/views/EditInfoPage/components/ModelEditInfoSection.tsx
  src/views/EditInfoPage/components/ModelInfo.tsx
  src/views/EditInfoPage/components/RegionList.tsx
  src/views/EditInfoPage/hooks/.gitkeep
  src/views/EditInfoPage/hooks/type.ts
  src/views/EditInfoPage/hooks/useGetModelUser.ts
  src/views/EditInfoPage/hooks/useGetRegionList.ts
  src/views/SignUpPage/hooks/.gitkeep
Labels: api 📡, EditPage🛠

#453 [EditPage] PUT API
  src/views/EditInfoPage/components/ModelEditInfoSection.tsx
  src/views/EditInfoPage/components/ModelInfo.tsx
  src/views/EditInfoPage/components/RegionList.tsx
  src/views/EditInfoPage/hooks/type.ts
  src/views/EditInfoPage/hooks/useGetModelUser.ts
  src/views/EditInfoPage/hooks/usePutModelUser.ts
Labels: api 📡, EditPage🛠
